# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true

stages:
- stage: dev
  jobs:

  - template: steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: dcibhprg
      workspacename: dcibhpws
      azureregion: $(azureregion) 
      aksimagename:  myimage
      project: "e2etestharness" 
      agent: $(agent)
      doCleanup: False

- stage: staging
  jobs:
  - template: steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: staging-pydl
      workspacename: stagingpydl
      azureregion: $(azureregion) 
      aksimagename:  staginghpaks
      project: "e2etestharness" 
      agent: $(agent)


- stage: tridant
  jobs:
  - template: steps/deploy.yml
    parameters:
      deployment_name: DLAKSDeployAMLJob
      template: DLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: tridant-pydl
      workspacename: tridantpydl
      azureregion: $(azureregion) 
      aksimagename: tridantpydlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
      agent: $(agent)

  - template: steps/deploy.yml
    parameters:
      deployment_name: MLAKSDeployAMLJob
      template: MLAKSDeployAMLJob.yml
      azureSubscription: $(devsub)
      azure_subscription: $(devsubid)
      azureresourcegroup: tridant-pyml
      workspacename: tridantpy
      azureregion: $(azureregion) 
      aksimagename:  tridantpymlaksimage
      doCleanup: False
      project: "e2etestharness" 
      expires : "DnD"
      alias: $(Build.RequestedForId)
      agent: AI-GPU
